### ISSUE TITLE
Do not parse the response, let the user do it manually

### ISSUE THREAD

**Issue by loicraux** [ajaishankar/openapi-typescript-fetch#27]
To better stick to `fetch` or `node-fetch` specs, the responsability to parse the JSON response should be left to the user...
(In `fetch` specs, this is done by calling the async API `response.json()`)

The problem in `openapi-typescript-fetch` code is that the corresponding async `getResponseData` API [is always called](https://github.com/ajaishankar/openapi-typescript-fetch/blob/main/src/fetcher.ts#L152), no matter what the returned HTTP code is.

This is causing issues, for example when an endpoint returns the HTTP code 204 (no content) with a zero bytes response body, which is totally valid. In this case [this line](https://github.com/ajaishankar/openapi-typescript-fetch/blob/main/src/fetcher.ts#L139) will throw an exception (actually thrown by `node-fetch` implementation).

A simple (but breaking) fix is to return a json() async function in the returned result of `fetchJson` :

```ts
async function fetchJson(url: string, init: RequestInit): Promise<ApiResponse> {
  const response = await fetch(url, init)

  if (response.ok) {
    return {
      headers: response.headers,
      url: response.url,
      ok: response.ok,
      status: response.status,
      statusText: response.statusText,
      json: async (): Promise<any> => await getResponseData(response)
    };
  }

  throw new ApiError(result)
}
```

And --from looking at the above code-- why not simply returning the `response` object if `response.ok` is true ?
(IMHO, `getResponseData` should disappear)

Your feedback is welcome!
Apart from that, thank you very much for this very useful library!

**Comment by ajaishankar** [comment]
Hi @loicraux thanks for pointing this issue.

Just published version 1.1.3 which includes a fix for 204 no content (https://github.com/ajaishankar/openapi-typescript-fetch/commit/a32b75b59b4acf167564ba5ef84d21a6fa64ea15)

The objective of the library is to make sure responses are typed and handled without too much of an effort from the caller, and any non ok response throws an error similar to axios.

Since 204 is special, it is easy an fix without having to introduce a breaking change (await json)
