### ISSUE TITLE
.create() incorrectly expects single argument

### ISSUE THREAD

**Issue by duncanbeevers** [ajaishankar/openapi-typescript-fetch#28]
### 🗣 Discussion

Defining and OpenAPI3 operation with both a requestBody and query causes the `.create()` signature to expect an argument for the query portion.

```ts
export type paths = {
  '/openapiv3/body': {
    post: {
      parameters: {
        path: { id: number }
        query: { name: string }
      }
      requestBody: {
        content: {
          'application/json': { 200: { schema: Data } }
        }
      }
    }
  }
}

const fetcher = Fetcher.for<paths>()
fetcher.path('/openapiv3/body').method('post').create()
// Expected 1 arguments, but got 0.
```

![image](https://user-images.githubusercontent.com/7367/167994319-5a167508-a0ec-46e4-b9df-8cf2a20538e2.png)

**Comment by ajaishankar** [comment]
@duncanbeevers this is by design.

When there is both a query and request body then the library needs to know what params to pass in query vs body when the method is called.

To handle this, we need to provide a hint via the extra argument at time of _creating_ a fetcher.

See [test](https://github.com/ajaishankar/openapi-typescript-fetch/blob/main/test/fetch.test.ts#L82) here
