### ISSUE TITLE
Post with 201 response appears as "unknown" type

### ISSUE THREAD

**Issue by bnhovde** [ajaishankar/openapi-typescript-fetch#5]
Hi! Me again.

I think I found another tiny bug. A POST that returns with a 201 response gives me this: `ApiResponse<unknown>`

PS: If i change it to 200 the type appears.

**Comment by ajaishankar** [comment]
@bnhovde Published new version that checks for 201 if 200 is missing (https://github.com/ajaishankar/openapi-typescript-fetch/commit/90dded8b2f7560923effe117d4f9643b1020da7b)

201 usually puts the url to the created resource in the Location header, but since response body can also be specified guess no harm in checking for this status code.
